"""Apply a patch (generated by differ_patch) to a CSV dataset.

Given an original list of row dicts and a Patch object, this module
produces a new list of rows that reflects all additions, removals, and
modifications described in the patch.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from csvdiff.differ_patch import Patch


class ApplyError(Exception):
    """Raised when a patch cannot be cleanly applied to the dataset."""


def _index_rows(rows: List[Dict], key_column: str) -> Dict[str, Dict]:
    """Return a mapping of key-value -> row dict for fast lookup.

    Raises ApplyError if duplicate keys are found.
    """
    index: Dict[str, Dict] = {}
    for row in rows:
        key = row.get(key_column)
        if key is None:
            raise ApplyError(
                f"Row is missing key column '{key_column}': {row}"
            )
        if key in index:
            raise ApplyError(
                f"Duplicate key '{key}' found in dataset — cannot apply patch."
            )
        index[key] = row
    return index


def apply_patch(
    rows: List[Dict],
    patch: Patch,
    key_column: Optional[str] = None,
    strict: bool = True,
) -> List[Dict]:
    """Apply *patch* to *rows* and return the resulting dataset.

    Parameters
    ----------
    rows:
        The original CSV rows as a list of dicts (e.g. from ``read_csv``).
    patch:
        A :class:`~csvdiff.differ_patch.Patch` instance produced by
        ``build_patch``.
    key_column:
        The column used as the unique row identifier.  Falls back to
        ``patch.key_column`` when *None*.
    strict:
        When *True* (default) an :class:`ApplyError` is raised if a
        patch operation references a row that does not exist (or already
        exists for additions).  Set to *False* to silently skip such
        conflicts.

    Returns
    -------
    list[dict]
        The patched rows in their original order, with additions appended
        at the end.
    """
    key_col = key_column or patch.key_column
    if not key_col:
        raise ApplyError("key_column must be provided either via the patch or explicitly.")

    index = _index_rows(rows, key_col)
    # Work on a mutable copy so we don't mutate the caller's data.
    result: Dict[str, Dict] = {k: dict(v) for k, v in index.items()}
    # Track insertion order so additions are appended at the end.
    order: List[str] = list(index.keys())

    for change in patch.changes:
        change_type = change.get("change_type")
        key = change.get("key")

        if change_type == "added":
            if key in result:
            	if strict:
                    raise ApplyError(
                        f"Cannot add row with key '{key}': already exists."
                    )
            else:
                new_row = {k: v for k, v in change.items() if k != "change_type"}
                result[key] = new_row
                order.append(key)

        elif change_type == "removed":
            if key not in result:
                if strict:
                    raise ApplyError(
                        f"Cannot remove row with key '{key}': not found."
                    )
            else:
                del result[key]
                order.remove(key)

        elif change_type == "modified":
            if key not in result:
                if strict:
                    raise ApplyError(
                        f"Cannot modify row with key '{key}': not found."
                    )
            else:
                field_changes: Dict = change.get("fields", {})
                for field, values in field_changes.items():
                    # values is expected to be {"old": ..., "new": ...}
                    result[key][field] = values.get("new")
        else:
            if strict:
                raise ApplyError(f"Unknown change_type '{change_type}' in patch.")

    # Reconstruct ordered list, skipping removed rows.
    return [result[k] for k in order if k in result]


def apply_summary(original: List[Dict], patched: List[Dict], key_column: str) -> str:
    """Return a one-line human-readable summary of what changed after applying a patch."""
    orig_keys = {r[key_column] for r in original}
    new_keys = {r[key_column] for r in patched}
    added = len(new_keys - orig_keys)
    removed = len(orig_keys - new_keys)
    modified = sum(
        1
        for r in patched
        if r[key_column] in orig_keys
        and r != next((o for o in original if o[key_column] == r[key_column]), r)
    )
    return (
        f"Patch applied: {added} added, {removed} removed, {modified} modified "
        f"({len(patched)} total rows)."
    )
